# Generated by Django 4.2.16 on 2024-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_transactions', '0002_remove_transactions_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiving_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sending_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
