# Generated by Django 4.2.16 on 2024-10-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_transactions', '0003_transactions_amount_transactions_receiving_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='sending_address',
        ),
    ]
