# Generated by Django 4.2.16 on 2024-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_transactions', '0006_alter_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receiving_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sending_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
