# Generated by Django 4.2.16 on 2024-11-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_transactions', '0007_alter_transactions_receiving_address_and_more'),
        ('my_transactions', '0007_alter_transactions_user'),
    ]

    operations = [
    ]
