# Generated by Django 4.2.16 on 2024-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='n/a', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
