# Generated by Django 4.2.16 on 2024-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
