# Generated by Django 4.2.16 on 2024-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0010_remove_profile_receiving_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receiving_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sending_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
