# Generated by Django 4.2.16 on 2024-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0012_alter_profile_receiving_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
