# Generated by Django 4.2.16 on 2024-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0013_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
