# Generated by Django 4.2.16 on 2024-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0014_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
