# Generated by Django 4.2.16 on 2024-11-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0015_profile_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletion_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
