# Generated by Django 4.2.16 on 2024-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0016_profile_deletion_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProfileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
