# Generated by Django 4.2.16 on 2024-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0018_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='ip_address',
            field=models.GenericIPAddressField(default='n/a'),
        ),
    ]
