# Generated by Django 4.2.16 on 2024-11-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0020_alter_userlocation_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
