# Generated by Django 4.2.16 on 2024-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0021_delete_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
