# Generated by Django 4.2.16 on 2024-11-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0022_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.TextField(blank=True, default=''),
        ),
    ]
