# Generated by Django 4.2.16 on 2024-11-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0023_alter_profile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deletion_request_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deletion_requested',
        ),
    ]
